customers-- MySQL Script generated by MySQL Workbench
-- Sun May 26 20:04:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bookstore` ;

-- -----------------------------------------------------
-- Schema bookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookstore` DEFAULT CHARACTER SET utf8 ;
USE `bookstore` ;

-- -----------------------------------------------------
-- Table `bookstore`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`Customers` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`Customers` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `money` DECIMAL(10,2) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Managers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`Managers` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`Managers` (
  `mid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`mid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookstore`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bookstore`.`Books` ;

CREATE TABLE IF NOT EXISTS `bookstore`.`Books` (
  `bid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `img` BLOB(0) NULL,
  `number` INT NULL,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
